services:
  - type: web
    name: bytefrost-backend
    runtime: docker
    plan: free
    dockerfilePath: ./backend/Dockerfile
    dockerContext: ./backend
    autoDeployTrigger: commit
    healthCheckPath: /health
    envVars:
      - key: DATABASE_URL
        fromDatabase:
          name: bytefrost-db
          property: connectionString
      - key: SECRET_KEY
        generateValue: true
      - key: ENVIRONMENT
        value: production
      - key: JWT_ALGORITHM
        value: HS256
      - key: JWT_EXPIRATION_MINUTES
        value: "30"
      - key: CORS_ORIGINS
        value: '["https://kisansetu-bay.vercel.app","https://kisansetu-dg8lmxbis-la-masia1.vercel.app"]'
databases:
  - name: bytefrost-db
    plan: free
    ipAllowList: []
