"""initial schema

Revision ID: bbc8c3fdaeae
Revises: 
Create Date: 2026-08-26 22:44:00.696376
"""
from typing import Sequence, Union
from alembic import op
import sqlalchemy as sa


revision: str = 'bbc8c3fdaeae'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('users',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('email', sa.String(length=255), nullable=False),
    sa.Column('phone', sa.String(length=20), nullable=True),
    sa.Column('full_name', sa.String(length=255), nullable=False),
    sa.Column('hashed_password', sa.String(length=255), nullable=False),
    sa.Column('role', sa.Enum('FARMER', 'FPO_MANAGER', 'BUYER_BULK', 'BUYER_RETAILER', 'CONSUMER', 'LOGISTICS', 'ADMIN', name='userrole'), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.Column('is_verified', sa.Boolean(), nullable=True),
    sa.Column('avatar_url', sa.String(length=500), nullable=True),
    sa.Column('address', sa.Text(), nullable=True),
    sa.Column('latitude', sa.Float(), nullable=True),
    sa.Column('longitude', sa.Float(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('phone')
    )
    op.create_index(op.f('ix_users_email'), 'users', ['email'], unique=True)
    op.create_table('fpos',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('registration_number', sa.String(length=100), nullable=True),
    sa.Column('address', sa.Text(), nullable=True),
    sa.Column('latitude', sa.Float(), nullable=True),
    sa.Column('longitude', sa.Float(), nullable=True),
    sa.Column('contact_user_id', sa.UUID(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['contact_user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('registration_number')
    )
    op.create_table('orders',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('buyer_id', sa.UUID(), nullable=False),
    sa.Column('status', sa.Enum('PENDING', 'CONFIRMED', 'ALLOCATED', 'DISPATCHED', 'IN_TRANSIT', 'DELIVERED', 'CANCELLED', name='orderstatus'), nullable=True),
    sa.Column('total_amount', sa.Float(), nullable=True),
    sa.Column('delivery_address', sa.Text(), nullable=True),
    sa.Column('delivery_latitude', sa.Float(), nullable=True),
    sa.Column('delivery_longitude', sa.Float(), nullable=True),
    sa.Column('delivery_deadline', sa.DateTime(), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['buyer_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('payments',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('order_id', sa.UUID(), nullable=False),
    sa.Column('payer_id', sa.UUID(), nullable=False),
    sa.Column('payee_id', sa.UUID(), nullable=False),
    sa.Column('amount', sa.Float(), nullable=False),
    sa.Column('status', sa.String(length=50), nullable=True),
    sa.Column('payment_method', sa.String(length=50), nullable=True),
    sa.Column('transaction_id', sa.String(length=255), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['order_id'], ['orders.id'], ),
    sa.ForeignKeyConstraint(['payee_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['payer_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('produce_listings',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('seller_id', sa.UUID(), nullable=False),
    sa.Column('fpo_id', sa.UUID(), nullable=True),
    sa.Column('crop_name', sa.String(length=255), nullable=False),
    sa.Column('variety', sa.String(length=255), nullable=True),
    sa.Column('quantity_kg', sa.Float(), nullable=False),
    sa.Column('quality_grade', sa.String(length=50), nullable=True),
    sa.Column('price_per_kg', sa.Float(), nullable=True),
    sa.Column('harvest_date', sa.DateTime(), nullable=True),
    sa.Column('availability_start', sa.DateTime(), nullable=True),
    sa.Column('availability_end', sa.DateTime(), nullable=True),
    sa.Column('pickup_location', sa.Text(), nullable=True),
    sa.Column('pickup_latitude', sa.Float(), nullable=True),
    sa.Column('pickup_longitude', sa.Float(), nullable=True),
    sa.Column('images', sa.JSON(), nullable=True),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['fpo_id'], ['fpos.id'], ),
    sa.ForeignKeyConstraint(['seller_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('allocations',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('order_id', sa.UUID(), nullable=False),
    sa.Column('listing_id', sa.UUID(), nullable=False),
    sa.Column('quantity_kg', sa.Float(), nullable=False),
    sa.Column('score', sa.Float(), nullable=True),
    sa.Column('explanation', sa.JSON(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['listing_id'], ['produce_listings.id'], ),
    sa.ForeignKeyConstraint(['order_id'], ['orders.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('order_items',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('order_id', sa.UUID(), nullable=False),
    sa.Column('listing_id', sa.UUID(), nullable=False),
    sa.Column('quantity_kg', sa.Float(), nullable=False),
    sa.Column('price_per_kg', sa.Float(), nullable=False),
    sa.ForeignKeyConstraint(['listing_id'], ['produce_listings.id'], ),
    sa.ForeignKeyConstraint(['order_id'], ['orders.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('shipments',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('allocation_id', sa.UUID(), nullable=False),
    sa.Column('logistics_provider_id', sa.UUID(), nullable=True),
    sa.Column('status', sa.String(length=50), nullable=True),
    sa.Column('route_plan', sa.JSON(), nullable=True),
    sa.Column('estimated_distance_km', sa.Float(), nullable=True),
    sa.Column('estimated_duration_min', sa.Float(), nullable=True),
    sa.Column('actual_distance_km', sa.Float(), nullable=True),
    sa.Column('actual_duration_min', sa.Float(), nullable=True),
    sa.Column('pickup_latitude', sa.Float(), nullable=True),
    sa.Column('pickup_longitude', sa.Float(), nullable=True),
    sa.Column('drop_latitude', sa.Float(), nullable=True),
    sa.Column('drop_longitude', sa.Float(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['allocation_id'], ['allocations.id'], ),
    sa.ForeignKeyConstraint(['logistics_provider_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('shipments')
    op.drop_table('order_items')
    op.drop_table('allocations')
    op.drop_table('produce_listings')
    op.drop_table('payments')
    op.drop_table('orders')
    op.drop_table('fpos')
    op.drop_index(op.f('ix_users_email'), table_name='users')
    op.drop_table('users')
    # ### end Alembic commands ###
